# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: CPUID.CPU-Z
PackageVersion: 1.96
MinimumOSVersion: 10.0.0.0
InstallModes:
  - interactive
  - silent
  - silentWithProgress
Installers:
  - Architecture: neutral
    InstallerType: exe
    InstallerUrl: https://download.cpuid.com/cpu-z/cpu-z_1.96-en.exe
    InstallerSha256: 2cb546e35198bc7b4e91439a47c33541a18c20ff87f723148bba250a9f91bb05
    InstallerSwitches:
      #Custom: 
      Silent: /verysilent
      SilentWithProgress: /silent
    #ProductCode: 
    Scope: machine
    InstallerLocale: en-US
    UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
