# Automatically updated by the winget bot at 2020/Dec/14
Id: XnSoft.XnViewMP
Version: 0.98.0
Name: XnViewMP
Publisher: XnSoft
License: GFL SDK/GflAx
LicenseUrl: https://www.xnview.com/wiki/index.php/License
AppMoniker: xnviewmp
Description: The enhanced Image Viewer for (Windows/MacOS/Linux)
Homepage: https://www.xnview.com/en/xnviewmp/
Installers:
- Arch: x64
  Url: https://download.xnview.com/XnViewMP-win-x64.exe
  Sha256: 0C8ECBDF5EA301DE987D324CBDC253CDD542B7B4A2ADC4326CC8A9F8374E9897
  InstallerType: inno
