# Automatically updated by the winget bot at 2020/Dec/26
Id: KCSoftwares.SUMo
Version: 5.12.1.473
Name: SUMo
Publisher: KC Softwares
License: Copyright (c) KC Softwares
Tags: software, update, monitor
Description: SUMo (Software Update Monitor) keeps your PC up-to-date & safe by using the most recent version of your favorite software !
Homepage: https://kcsoftwares.com/?sumo
Installers:
- Arch: x64
  Url: https://kcsoftwares.com/files/sumo_lite.exe
  Sha256: 3422E1C8342E17D5C2E12B99420D66063E5086AE756F053B075F437CA06ABE28
  InstallerType: Inno
