PackageIdentifier: TimKosse.FileZillaClientNightly
PackageName: FileZilla Client Nightly
Moniker: filezilla-nightly
PackageVersion: 3.54.0-rc1-20210508
Publisher: Tim Kosse
Author: Tim Kosse
License: (c) 2021 Tim Kosse
LicenseUrl: https://filezilla-project.org/license.php
ShortDescription: FileZilla Client is a fast and reliable cross-platform FTP, FTPS and SFTP client with lots of useful features and an intuitive graphical user interface.
PackageUrl: https://filezilla-project.org/
Installers:
- Architecture: x64
  InstallerUrl: https://filezilla-project.org/nightlies/2021-05-08/win64/FileZilla_3_setup.exe
  InstallerSha256: 92819e11f87363ed93266d2c24d9f0734339f996bd2224560c3619fa740f8639
  InstallerType: nullsoft
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
