# Automatically updated by the winget bot at 2020/Dec/17
Id: Heroku.HerokuCLI
Version: 7.47.6.0
Name: HerokuCLI
AppMoniker: heroku
Publisher: Heroku
License: ISC License
LicenseUrl: https://github.com/heroku/cli/blob/master/LICENSE
Description: The Heroku Command Line Interface (CLI) makes it easy to create and manage your Heroku apps directly from the terminal. It is an essential part of using Heroku.
Homepage: https://devcenter.heroku.com/articles/heroku-cli
Installers:
- Arch: x64
  Url: https://cli-assets.heroku.com/heroku-x64.exe
  Sha256: EDFB11DA490F0D1F5A43602896FA979E9DBA3B2D2E1BA06F23B5B248466B4954
  InstallerType: nullsoft
