# Automatically updated by the winget bot at 2020/Dec/07
Id: Mega.MEGASync
Publisher: Mega Limited
Name: MEGASync
AppMoniker: mega
Description: Easy automated synchronisation between your computer and your MEGA cloud.
Homepage: https://mega.nz/sync
Tags: Sync, Synchronization, File Sync, Cloud, Transfer
License: Proprietary
LicenseUrl: https://github.com/meganz/MEGAsync/blob/master/LICENCE.md
Version: 4.3.8.0
InstallerType: nullsoft
Installers:
- Arch: x64
  Url: https://mega.nz/MEGAsyncSetup.exe?v=4.3.3.0
  Sha256: 25739EC9823C7483811B2C51F8DE4836DBAF5E94EE839555FE13C8076DD0B114
