# Automatically updated by the winget bot at 2020/Dec/09
Id: TIDAL.TIDAL
Publisher: TIDAL Music AS
Name: TIDAL
Version: 2.23.0
AppMoniker: TIDAL
MinOSVersion: 10.0.0.0
Description: TIDAL is a global music streaming service with high fidelity sound, hi-def video quality, and expertly curated playlists.
Homepage: https://tidal.com
License: Copyright (c) 2020 Aspiro AB
InstallerType: exe
Installers:
- Arch: x64
  Url: https://download.tidal.com/desktop/TIDALSetup.exe
  Sha256: 604432EA8BE8221770F50FAD91BC980BF00D316002BAFDA5090EA073CF872E30
ManifestVersion: 0.1.0
