Id: CrystalDewWorld.CrystalDiskMarkShizukuEdition
Publisher: Crystal Dew World
Name: CrystalDiskMark Shizuku Edition
Version: 8.0.0a
Author: hiyohiyo
License: MIT
LicenseUrl: https://crystalmark.info/en/software/crystaldiskmark/crystaldiskmark-license/
Homepage: https://crystalmark.info/en/software/crystaldiskmark/
Tags: utility
Description: CrystalDiskMark is a simple disk benchmark software.
InstallerType: inno
Installers:
  - Arch: x64
    Url: https://osdn.net/frs/redir.php?m=ymu&f=crystaldiskmark%2F73958%2FCrystalDiskMark8_0_0aShizuku.exe
    Sha256: 57a4b4065ae85d581d105299f043a6b969844c98abf980f94b08e73471ab5102
    Switches:
      Silent: /VERYSILENT
      SilentWithProgress: /VERYSILENT
