# Automatically updated by the winget bot at 2020/Dec/17
Id: Ubisoft.Connect
Publisher: Ubisoft
Name: Ubisoft Connect
Author: Ubisoft
Description: Ubisoft Connect is the ecosystem of players services for Ubisoft games across all platforms. It aims at giving the best environment for all players to enjoy their games and connect with each other whatever the device.
AppMoniker: connect
Tags: games, uplay, connect, store, purchase
Homepage: https://ubisoftconnect.com/
License: © Ubisoft Entertainment. All Rights Reserved.
LicenseUrl: https://legal.ubi.com/LegalInfoUbisoftEMEA
MinOSVersion: 10.0.0.0
Version: 117.0.0.10324
InstallerType: Nullsoft
Installers:
- Arch: x86
  Url: https://ubistatic3-a.akamaihd.net/orbit/launcher_installer/UbisoftConnectInstaller.exe
  Sha256: 4A1BC69EAA1091870BD3F58FD6A06BF2C535C23AE1037CA0B4F0EE08B0C74F8D
