# Automatically updated by the winget bot at 2020/Dec/21
Id: Fork.Fork
Version: 1.57.1
Name: Fork
Publisher: Fork
License: Copyright (c) 2020 Dan Pristupov
LicenseUrl: https://git-fork.com/license
AppMoniker: git-fork
Tags: git
Description: A fast and friendly git client for Mac and Windows.
Homepage: https://git-fork.com
Installers:
- Arch: x86
  Url: https://git-fork.com/update/win/ForkInstaller.exe
  Sha256: ED34F66A4E9F9B7B997E43124034FE5AC7762049F617F91610EBF3C1F51C4563
  InstallerType: exe
  Switches:
    Silent: /s
    SilentWithProgress: /s
