# Automatically updated by the winget bot at 2020/Dec/09
Id: Nlitesoft.NTLite
Publisher: Nlitesoft
Name: NTLite
Version: 2.0.0.7742
License: © 2014-2020 Nlitesoft
InstallerType: EXE
AppMoniker: ntlite
Tags: Windows setup
Description: Integrate updates, drivers, automate Windows and application setup, speedup Windows deployment process and have it all set for the next time.
Homepage: https://www.ntlite.com/
Installers:
- Arch: x64
  InstallerType: inno
  Url: http://downloads.ntlite.com/files/NTLite_setup_x64.exe
  Sha256: 48E850178C26252361E898E4269A255A3DB3DAF5066C3E9B04E01A74D45BFBCC
