Id: Quicken.Quicken
Version: latest # 27.1.30.14
Name: Quicken
Publisher: Quicken
License: Copyright (c) Quicken Inc.
AppMoniker: quicken
Tags: quicken, money, qw
Description: Quicken is a personal finance management tool that can be used to record banking transactions, planning a budget and tracking investments.
Homepage: https://www.quicken.com
Installers:
  - Arch: x86
    Url: https://download.quicken.com/windows/Quicken.exe
    Sha256: 4DB159DEF9CEFA9467BF6DA6FCC32D319E1ABDE4CBAD18C1DBCECB246438D369
    InstallerType: exe
    ProductCode: "{62D93E3E-2F8E-42BD-9343-896F4F0031D3}"
    Switches:
        Silent: "/s /a /s"
        SilentWithProgress: "/s /a /s"

