---
Id: Amazon.WorkspacesClient
Version: latest # 3.1.0
Name: Amazon Workspaces Client
Publisher: Amazon
License: Copyright (c) Amazon Web Services, Inc.
LicenseUrl: https://clients.amazonworkspaces.com/app-terms.html
AppMoniker: workspaces
Tags: amazon, workspaces, rdp
Description: Amazon WorkSpaces offers an easy way to provide a cloud-based desktop experience to your end users.
Homepage: https://aws.amazon.com/workspaces/
Installers:
  - Arch: x64
    Url: https://d2td7dqidlhjx7.cloudfront.net/prod/global/windows/Amazon+WorkSpaces.msi
    Sha256: 1D8F2F8C66B615E0C936530C427DDF84B1A6085033E81F0708E58E5AE2A2471C
    InstallerType: msi
    ProductCode: "{50B4E741-9A63-4F42-8B37-59F09111FAD7}"

