# ================== General ==================
Id: AIMP.AIMP
Publisher: AIMP
Name: AIMP
Author: Artem Izmaylov, Mike Green
Description: AIMP is a freeware audio player
AppMoniker: aimp
Tags: audio player, music player
FileExtensions: CDA, AAC, AC3, APE, DTS, FLAC, IT, MIDI, MO3, MOD, M4A, M4B, MP1, MP2, MP3, MPC, MTM, OFR, OGG, OPUS, RMI, S3M, .SPX, TAK, TTA, UMX, WAV, WMA, WV, XM

# ================== License ==================
Homepage: https://www.aimp.ru
License: LGPLv2.1 - © Artem Izmaylov 2006-2020 | All rights reserved
LicenseUrl: https://www.aimp.ru/files/windows/EULA_lang-en.txt

# ================= Installer =================
MinOSVersion: 10.0.0.0
#Channel: stable                # Channel is not supported in this preview (5/24/2020)
Version: 4.70.2236

Switches:
      #Custom:
      Silent: "/AUTO /SILENT"
      SilentWithProgress: "/AUTO"
      #Interactive:
      Language: en-US

InstallerType: exe
Installers:
  - Arch: x86
    Url: https://aimp.su/storage/c93aed3876425b38cd8191714e3a9b2b/aimp_4.70.2236.exe
    Sha256: 5db475ad8ef05976add3bdf1eac31a499c85fd90611f7cd4588de12fbc10ac0e
    Scope: machine
    
# ManifestVersion: 0.1.0

