# ================== General ==================
Id: KDE.KDEConnect 
Publisher: KDE
Name: KDE Connect
Author: KDE
Description: Enabling communication between all your devices. Made for people like you.
#AppMoniker: 
Tags: connect,phone,mobile,android,notification
#FileExtensions: 
#Protocols: 

# ================== License ==================
Homepage: https://kdeconnect.kde.org/
License: GPL-2.0 
#LicenseUrl: 

# ================= Installer =================
Version: 1.4-441
InstallerType: appx
Installers:
  - Arch: x64
    Url: https://binary-factory.kde.org/job/kdeconnect-kde_Release_win64/lastSuccessfulBuild/artifact/kdeconnect-kde-1.4-441-windows-msvc2019_64-cl-sideload.appx
    Sha256: b0dcd61db37f506d789bbd82c826ec78d71a2c0a6ff66178b0a1bf6ffc4f459c
    #Switches:
    #  Silent: 
    #  SilentWithProgress: 