Id: Oracle.VirtualBoxTest
Name: Oracle VM VirtualBox Test
AppMoniker: virtualbox-test
Version: 6.1.17-141652
Publisher: Oracle Corporation
Author: Oracle Corporation
License: (c) 2020 Oracle Corporation
LicenseUrl: https://www.virtualbox.org/wiki/Licensing_FAQ
Description: VirtualBox is a powerful x86 and AMD64/Intel64 virtualization product for enterprise as well as home use. Not only is VirtualBox an extremely feature rich, high performance product for enterprise customers, it is also the only professional solution that is freely available as Open Source Software under the terms of the GNU General Public License (GPL) version 2.
Homepage: https://www.virtualbox.org/
Installers:
  - Arch: x64
    Url: https://www.virtualbox.org/download/testcase/VirtualBox-6.1.17-141652-Win.exe
    Sha256: be84a4cab2cd96f784c89be21200d432ad31349dfd404fe740da9ee9308ac07e
    InstallerType: exe
    Switches:
      Silent: --silent
      SilentWithProgress: --silent
