# Automatically updated by the winget bot at 2020/Dec/24
Id: Huawei.Welink
Name: Welink
Version: 7.0.42
Publisher: Huawei
License: copyright (c) Huawei
LicenseUrl: https://www.huaweicloud.com/declaration/statement.html#
Homepage: https://www.huaweicloud.com/product/welink-download.html
Description: A unified communication and collaboration platform that combines persistent workplace chat and video meetings.
Tags: huawei,meeting,video,work,cloud,collaboration,electron
InstallerType: inno
Installers:
- Arch: x64
  Url: https://welink.huaweicloud.com/download/WeLink_setup.exe
  Sha256: 2CC35617B9EB42941AE015A01DF047A59DA97FDEA9D1B31511EA618CC1D585BD
