Id: Microsoft.VisualStudioCode
Version: 1.52.0.940b5f4bb5
Name: Visual Studio Code
Publisher: Microsoft Corporation
Homepage: https://code.visualstudio.com
License: Copyright (c) Microsoft Corporation
Description: Visual Studio Code is a code editor redefined and optimized for building and debugging modern web and cloud applications. Visual Studio Code is free and available on your favorite platform - Linux, macOS, and Windows.
AppMoniker: vscode
Commands: code
Installers: 
    - Arch: x64
      Url: https://az764295.vo.msecnd.net/stable/940b5f4bb5fa47866a54529ed759d95d09ee80be/VSCodeUserSetup-x64-1.52.0.exe
      InstallerType: inno
      Sha256: dfafe64a628b0ef76b706d10c3e6040093a1b8c27aa16b11cf268c551710df69
