# Automatically updated by the winget bot at 2020/Dec/23
Id: LINE.LINE
Name: LINE
Version: 6.5.2.2431
Publisher: LINE Corporation
Homepage: https://line.me/en-US/download
License: Copyright LINE Corporation All Rights Reserved.
Description: LINE reshapes communication around the globe, allowing you to enjoy not only messaging but also free voice and video calls wherever you find yourself. Download LINE and discover the reasons for its global popularity and number one ranking in 52 countries.
Tags: LINE, IM, Social
InstallerType: exe
Installers:
- Arch: x86
  Url: https://desktop.line-scdn.net/win/new/LineInst.exe
  Sha256: 8A452EEAEFF19AA59CC2D389D94D48DE24B4911AFA0E17AE8A0635B7F99DDE9F
  Switches:
    Silent: /M
    SilentWithProgress: /M
