Installers:
- Url: https://dist.memurai.com/releases/Memurai-Developer/2.0.3/Memurai-Developer-v2.0.3.msi
  Arch: x64
  Sha256: 1ffce44153b8047d5e67bbb73f397a9657ee25e023b214abaed53605f782dd81
License: Copyright (c) Memurai. All rights reserved.
InstallerType: msi
Homepage: https://www.memurai.com/
Publisher: Memurai
Name: MemuraiDeveloper
Version: 2.0.3
Id: Memurai.MemuraiDeveloper
Switches:
  Silent: /quiet
LicenseUrl: https://dist.memurai.com/releases/Memurai-Developer/2.0.3/MemuraiDeveloperFiles/Memurai-Developer-EULA.rtf
Tags: memurai, cache, redis-compatible, redis-client
Description: "Memurai is a Redis-5-compatible cache and data store for Windows. \nIt is designed to provide the reliability and performance demanded by enterprise Windows environments.\nJust like Redis, Memurai uses an in-memory data set to achieve great performance at scale, \nand Memurai supports all the Redis features that you know and love, such as persistence, \nreplication, transactions, LUA scripting, high-availability, pub/sub, cluster, modules, streams, and LRU eviction. \nIn fact, it supports all of the Redis API 5 eviction policies.\n"

