# Automatically updated by the winget bot at 2020/Dec/08
Id: Blade.Shadow
Version: 5.0.809.6322
Name: Shadow
Publisher: Blade
License: Copyright (c) Shadow by Blade
AppMoniker: shadow
Tags: streaming
Description: Video Game Streaming Service
Homepage: https://shadow.tech
Installers:
- Arch: x64
  Url: https://update.shadow.tech/launcher/prod/win/x64/ShadowSetup.exe
  Sha256: 7D427CBBECA7FE2E128883AE5F538281DFDEAE75A91F4B3855C846DBC9DB3BC5
  InstallerType: exe
  Switches:
    Silent: "/S"
    SilentWithProgress: "/S"
