# Automatically updated by the winget bot at 2021/May/03
PackageIdentifier: TorGuard.TorGuard
PackageVersion: latest
PackageName: TorGuard
Publisher: TorGuard
License: Copyright © 2020 TorGuard.net
Moniker: torguard
Tags:
- vpn openvpn
ShortDescription: TorGuard VPN Service encrypts your internet access
PackageUrl: https://torguard.net/
Installers:
- Architecture: x64
  InstallerUrl: https://torguard.net/downloads/torguard-setup-latest.exe
  InstallerSha256: 02AA1EE72D000EC41F476B3DDFFE85824E741DF7A9FA9B804A1655FA5BDBA6FF
  InstallerType: nullsoft
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
