# Automatically updated by the winget bot at 2020/Dec/10
Id: Google.DriveFileStream
Version: 44.0.14.0
Name: Drive File Stream
Publisher: Google, Inc.
License: Copyright (c) Google, Inc.
LicenseUrl: https://gsuite.google.com/terms/2013/1/premier_terms.html
AppMoniker: GoogleDriveFileStream
Tags: google, drive, filestream, sharedrive
Description: Mounts Google Drive(s) as a share drive and streams files as needed from the cloud. Alternative to Google Backup and Sync.
Homepage: https://support.google.com/a/answer/7491144?utm_medium=et&utm_source=aboutdrive&utm_content=getstarted&utm_campaign=en_us
Installers:
- Arch: x64
  Url: https://dl.google.com/drive-file-stream/GoogleDriveFSSetup.exe
  Sha256: 4DFAF8EE710F60A40A2902EE1FE62C180973E9E046968D3B7B4B88AE8B09C37E
  ProductCode: "{6BBAE539-2232-434A-A4E5-9A33560C6283}"
  InstallerType: exe
  Switches:
    Silent: --silent --gsuite_shortcuts=false
    SilentWithProgress: --silent --gsuite_shortcuts=false
