# Automatically updated by the winget bot at 2020/Dec/21
Id: Icons8.Lunacy
Version: 6.6.0
Name: Lunacy
Publisher: Icons8
License: © 2018 Icons8 LLC
LicenseUrl: https://icons8.com/license
AppMoniker: lunacy
Tags: icons8, lunacy
Description: Lunacy is a native Windows app that opens, edits, and stores .sketch files. And it’s completely free.
Homepage: https://icons8.com/lunacy
Installers:
- Arch: Neutral
  Url: https://desktop.icons8.com/lunacy/LunacySetup.exe
  Sha256: 1B5FBAF99D32DBF8A85EEDE2AD999A8F9B2E4C855F020505A14EAA8C6B00759A
  InstallerType: inno
  Switches:
    Silent: /VERYSILENT
    SilentWithProgress: /VERYSILENT
