Id: WiresharkFoundation.Wireshark
Publisher: WiresharkFoundation
Name: Wireshark
Author: WiresharkFoundation
Description: Wireshark is the world's foremost and widely-used network protocol analyzer. It lets you see what's happening on your network at a microscopic level and is the de facto (and often de jure) standard across many commercial and non-profit enterprises, government agencies, and educational institutions.
AppMoniker: wireshark
Tags: network, protocol, analyzer, sniffer
Homepage: https://www.wireshark.org/
License: GPL-2.0-or-later
LicenseUrl: https://github.com/wireshark/wireshark/blob/master/COPYING
MinOSVersion: 10.0.0.0
Version: 3.4.2.0

InstallerType: Nullsoft
Installers:
  - Arch: x64
    Url: https://2.na.dl.wireshark.org/win64/Wireshark-win64-3.4.2.exe
    Sha256: FAA98F833E10B450C24E42A42292FF894C36B97AEC526BF259796488888FD57C
    Scope: machine
