# Automatically updated by the winget bot at 2020/Dec/15
Id: TechSmith.Snagit
Name: Snagit
AppMoniker: Snagit
Version: 21.1.0.7764
Publisher: TechSmith
License: Copyright (C) 2020 TechSmith
MinOSVersion: 10.0.0.0
Homepage: https://www.techsmith.com/
Description: Screen Capture and Recording Software
Tags: "snagit,screen capture,recording"
Installers:
- Arch: x64
  Url: https://download.techsmith.com/snagit/releases/snagit.exe
  InstallerType: exe
  Sha256: FB1A945908BA021CEE438EBA3938FD767D5736F3AFE746F6548313D0973847F4
  Switches:
    Silent: /S
    SilentWithProgress: /S
