Id: Microsoft.VisualStudioCodeInsiders
Version: 1.52.16.6026ab576d
Name: Visual Studio Code - Insiders
Publisher: Microsoft Corporation
Homepage: https://code.visualstudio.com
License: Copyright (c) Microsoft Corporation
Description: Visual Studio Code is a code editor redefined and optimized for building and debugging modern web and cloud applications. Visual Studio Code is free and available on your favorite platform - Linux, macOS, and Windows.
AppMoniker: vscode-insiders
Commands: code-insiders
Installers: 
    - Arch: x64
      Url: https://az764295.vo.msecnd.net/insider/6026ab576dc6a4fbb8e255241a364816f42464c5/VSCodeUserSetup-x64-1.52.0-insider.exe
      InstallerType: inno
      Sha256: 2574a0691fb791fd5ea899e796bbbee4ec9084d38c198e97ad9d4d510a50fb16
