Id: Microsoft.VisualStudioCodeInsiders
Version: 1.53.3.f3e95ede9e
Name: Visual Studio Code - Insiders
Publisher: Microsoft Corporation
Homepage: https://code.visualstudio.com
License: Copyright (c) Microsoft Corporation
Description: Visual Studio Code is a code editor redefined and optimized for building and debugging modern web and cloud applications. Visual Studio Code is free and available on your favorite platform - Linux, macOS, and Windows.
AppMoniker: vscode-insiders
Commands: code-insiders
Installers: 
    - Arch: x64
      Url: https://az764295.vo.msecnd.net/insider/f3e95ede9e4b9818c29a5bca3564d6fd162fb210/VSCodeUserSetup-x64-1.53.0-insider.exe
      InstallerType: inno
      Sha256: 2c729ecb6e869a734518cdedfe8ee8885c9fe7b8216fb118b34a1d858070dc5d
