Id: Microsoft.VisualStudioCodeInsiders
Version: 1.53.7.c8aaeb7513
Name: Visual Studio Code - Insiders
Publisher: Microsoft Corporation
Homepage: https://code.visualstudio.com
License: Copyright (c) Microsoft Corporation
Description: Visual Studio Code is a code editor redefined and optimized for building and debugging modern web and cloud applications. Visual Studio Code is free and available on your favorite platform - Linux, macOS, and Windows.
AppMoniker: vscode-insiders
Commands: code-insiders
Installers: 
    - Arch: x64
      Url: https://az764295.vo.msecnd.net/insider/c8aaeb75137b8ec057d2676a22f7273a7a6a34a2/VSCodeUserSetup-x64-1.53.0-insider.exe
      InstallerType: inno
      Sha256: a288c830a75181072f3ea95a63c50be5cf88d2df4235ecfbf2c71a21634927d4
