Id: TimKosse.FileZillaClientNightly
Name: FileZilla Client Nightly
AppMoniker: filezilla-nightly
Version: 3.51.0-20201203
Publisher: Tim Kosse
Author: Tim Kosse
License: (c) 2020 Tim Kosse
LicenseUrl: https://filezilla-project.org/license.php
Description: FileZilla Client is a fast and reliable cross-platform FTP, FTPS and SFTP client with lots of useful features and an intuitive graphical user interface.
Homepage: https://filezilla-project.org/
Installers:
  - Arch: x64
    Url: https://filezilla-project.org/nightlies/2020-12-03/win64/FileZilla_3_setup.exe
    Sha256: 05933aaec78a41c910410bded3f8cfe22fc6ffe7a9c945b7be25d72ccc150f53
    InstallerType: nullsoft
    Switches:
      Silent: /S
      SilentWithProgress: /S
