Id: TimKosse.FileZillaClientNightly
Name: FileZilla Client Nightly
AppMoniker: filezilla-nightly
Version: 3.51.0-20201129
Publisher: Tim Kosse
Author: Tim Kosse
License: (c) 2020 Tim Kosse
LicenseUrl: https://filezilla-project.org/license.php
Description: FileZilla Client is a fast and reliable cross-platform FTP, FTPS and SFTP client with lots of useful features and an intuitive graphical user interface.
Homepage: https://filezilla-project.org/
Installers:
  - Arch: x64
    Url: https://filezilla-project.org/nightlies/2020-11-29/win64/FileZilla_3_setup.exe
    Sha256: 29152241e19c1ed69326a48e0729f3fb3605648b056c31ca9bcdfa1dea04c11e
    InstallerType: nullsoft
    Switches:
      Silent: /S
      SilentWithProgress: /S
