Id: TimKosse.FileZillaClientNightly
Name: FileZilla Client Nightly
AppMoniker: filezilla-nightly
Version: 3.52.0-beta1-20201224
Publisher: Tim Kosse
Author: Tim Kosse
License: (c) 2020 Tim Kosse
LicenseUrl: https://filezilla-project.org/license.php
Description: FileZilla Client is a fast and reliable cross-platform FTP, FTPS and SFTP client with lots of useful features and an intuitive graphical user interface.
Homepage: https://filezilla-project.org/
Installers:
  - Arch: x64
    Url: https://filezilla-project.org/nightlies/2020-12-24/win64/FileZilla_3_setup.exe
    Sha256: 4f7673c379f31fabe642819f3fe90bd0f1ced50187b88dbc83c9a93ee3d02d60
    InstallerType: nullsoft
    Switches:
      Silent: /S
      SilentWithProgress: /S
