# Automatically updated by the winget bot at 2020/Dec/09
Id: ColdTurkeySoftware.ColdTurkeyBlocker
Version: 4.1
Name: Cold Turkey Blocker
Publisher: Cold Turkey Software
License: Copyright (c) 2020 Cold Turkey Software
LicenseUrl: https://getcoldturkey.com/terms/
AppMoniker: coldturkeyblocker
Tags: blocker, coldturkey, distraction
Description: Boost your productivity and reclaim your free time by blocking distracting websites, games and applications.
Homepage: https://getcoldturkey.com
Installers:
- Arch: neutral
  Url: https://getcoldturkey.com/files/Cold_Turkey_Installer.exe
  Sha256: 1EC5EDA35F36586DF87382E497EE855ED0BDF4946B4867536C65D1F09FD24F04
  InstallerType: inno
  ProductCode: "{6498E673-B9C2-4544-A722-1E854B5B573E}"
