# Automatically updated by the winget bot at 2020/Dec/25
Id: SoftDeluxe.FreeDownloadManager
Version: 6.13.0.3463
Name: Free Download Manager
Publisher: SoftDeluxe
License: Copyright (c) SoftDeluxe Ltd.
LicenseUrl: https://www.freedownloadmanager.org/privacy.htm
AppMoniker: fdm
Tags: download manager
Description: Free Download Manager (FDM for short) is a free, efficient, and comprehensive solution for managing all your downloads.
Homepage: https://www.freedownloadmanager.org/
Installers:
- Arch: x64
  Url: https://dn3.freedownloadmanager.org/6/latest/fdm_x64_setup.exe
  Sha256: 12A25CF26E9E677E0E8CD3DF971062B99582560AE604C0132519F49F68BB82EC
  InstallerType: inno
  Switches:
    Silent: /ALLUSERS /VERYSILENT
    SilentWithProgress: /ALLUSERS /SILENT
