Id: Wireguard.Wireguard
Version: 0.3.1
Name: Wireguard
Publisher: Wireguard
License: Copyright © 2015-2020 JAson A. Donenfeld. All Rights Reserved
AppMoniker: wireguard
Tags: wireguard, vpn
Description: WireGuard® is an extremely simple yet fast and modern VPN that utilizes state-of-the-art cryptography.
Homepage: https://www.wireguard.com/
Installers:
  - Arch: x64
    Url: https://download.wireguard.com/windows-client/wireguard-amd64-0.3.1.msi
    Sha256: f0467b8dca14c578dcdf3362712c966b0d38c250fd9ab12f1c816ccdecd34312
    InstallerType: msi
