# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.0.0.schema.json
PackageIdentifier: ProtonTechnologies.ProtonVPN
PackageVersion: 1.20.3
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.0.0
