# Automatically updated by the winget bot at 2020/Dec/08
Id: Nvidia.GeForceNow
Publisher: Nvidia
Name: Nvidia GeForce Now
Author: Nvidia
Description: GeForce NOW instantly transforms nearly any laptop, desktop, Mac, SHIELD TV or Android mobile device into the PC gaming rig you've always dreamed of. Instantly play the most demanding PC games and seamlessly play across your devices.
AppMoniker: geforcenow
Tags: games, streaming
Homepage: https://www.nvidia.com/en-us/geforce-now/
License: Copyright © 2020 NVIDIA Corporation
LicenseUrl: https://www.nvidia.com/en-us/about-nvidia/nvidia-geforce-now-terms-of-use/
MinOSVersion: 10.0.0.0
Version: 1.0.9
Switches:
  Custom: -noreboot
  Silent: -s
  SilentWithProgress: -s
  Language: en-US
InstallerType: exe
Installers:
- Arch: x86
  Url: https://download.nvidia.com/gfnpc/GeForceNOW-release.exe
  Sha256: 2434F0F7B9C550AA6A01EAD47D9156EBF2538F1B9E3795951AB4055F5B84BC63
  Scope: user
